# Generated by Django 4.1.4 on 2023-01-17 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=52)),
                ('continent', models.CharField(max_length=13)),
                ('region', models.CharField(max_length=26)),
                ('surfacearea', models.DecimalField(decimal_places=2, max_digits=10)),
                ('indepyear', models.SmallIntegerField(blank=True, default='', null=True)),
                ('population', models.IntegerField()),
                ('lifeexpectancy', models.DecimalField(blank=True, decimal_places=1, default='', max_digits=3, null=True)),
                ('gnp', models.DecimalField(blank=True, decimal_places=2, default='', max_digits=10, null=True)),
                ('gnpold', models.DecimalField(blank=True, decimal_places=2, default='', max_digits=10, null=True)),
                ('localname', models.CharField(max_length=45)),
                ('governmentform', models.CharField(max_length=45)),
                ('headofstate', models.CharField(blank=True, default='', max_length=60, null=True)),
                ('capital', models.IntegerField(blank=True, default='', null=True)),
                ('code2', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Countrylanguage',
            fields=[
                ('countrycode', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='country.country')),
                ('language', models.CharField(max_length=30)),
                ('isofficial', models.CharField(max_length=1)),
                ('percentage', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('district', models.CharField(max_length=20)),
                ('population', models.IntegerField()),
                ('countrycode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.country')),
            ],
        ),
    ]
